config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'home/index'
  get 'home/profile'
  get 'download/import_xls/:name', to: 'download#import_xls', as: :download_import_xls

  resources :salesman_day_tradetotals
  resource :report do
    collection do
      get :clients_days
      get :new_clients
      get :active_clients
      get :active_agents
      get :home_summary
    end
  end
  resources :jobs do
    collection do
      get 'run_job/:job', action: :run_job, as: :run_job
      get 'recal'
    end
  end
  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    member do
      get :create_login
      get :del_login
      get :del_salesman
      get :add_salesman
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades do
    collection do
      get 'client_trades/:client_id', to: 'trades#client_trades'
    end
  end
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen do
    member do
      get :set_client
    end
  end
  resources :pos_machines

  # raw data
  resources :imp_ops
  resources :imp_logs do
    member do
      get :import, :unimport, :total, :untotal
    end
  end
  resources :imp_qf_clearings
  resources :imp_qf_trades
  resources :imp_qf_customers
  resources :code_tables
  resource :summary do
    member do
      get :home_sum
    end
  end
  resources :logs do
    collection do
      get :get_log_msg
    end
  end
  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  root to: 'home#index'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  # 特殊修改: 在修改object的时候设置了  publisher_id

  
  # GET /notices
  # GET /notices.json
  def index
    @collection = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @object = Notice.new
    @object.publisher_id = current_user.id

  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @object = Notice.new(notice_params)
    @object.publisher_id = current_user.id


    respond_to do |format|
      if @object.save
        format.html { redirect_to @object, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @object }
      else
        format.html { render :new }
        format.json { render json: @object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update

    respond_to do |format|
      if @object.update(notice_params)
        @object.publisher_id = current_user.id

        format.html { redirect_to @object, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @object }
      else
        format.html { render :edit }
        format.json { render json: @object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @object.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @object = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:publish_date, :close_date, :title, :content)
    end
end

app/views/notices/_form.html.slim
= form_for(@object) do |f|
  - if @object.errors.any?
    #error_explanation
      h2
        = pluralize(@object.errors.count, "error")
        |  prohibited this bulletin_board_system from being saved:
      ul
        - @object.errors.full_messages.each do |message|
          li
            = message
  /
  .field
    = f.label :publish_date
    br
    = f.datetime_select :publish_date
  .field
    = f.label :close_date
    br
    = f.datetime_select :close_date
  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :content
    br
    = f.text_area :content, cols: 100, rows: 10
  .field
    = f.label :publisher_id
    br
    = f.text_field :publisher_id
  .actions
    = f.submit

app/views/notices/edit.html.slim
h1
  | Editing Bulletin Board System
= render 'form'
= link_to 'Show', @object
|  | 
= link_to 'Back', notices_path

app/views/notices/index.html.slim
p#notice
  = notice
h1
  | Listing Bulletin Board Systems
table.table
  thead
    tr
      th
        | publish_date
      th
        | close_date
      th
        | Title
      th
        | Content
      th
        | Publisher
      th[colspan="3"]
  tbody
    - @collection.each do |r|
      tr
        td
          = r.publish_date
        td
          = r.close_date
        td
          = r.title
        td
          = r.content
        td
          = r.publisher_id
        td
          = link_to 'Show', r
        td
          = link_to 'Edit', edit_notice_path(r)
        td
          = link_to 'Destroy', r, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Bulletin board system', new_notice_path

app/views/notices/new.html.slim
h1
  | New Bulletin Board System
= render 'form'
= link_to 'Back', notices_path

app/views/notices/show.html.slim
p#notice
  = notice
p
  strong
    | publish_date:
  = @object.publish_date
p
  strong
    | close_date:
  = @object.close_date
p
  strong
    | Title:
  = @object.title
p
  strong
    | Content:
  = @object.content
p
  strong
    | Publisher:
  = @object.publisher_id
= link_to 'Edit', edit_notice_path(@object)
|  | 
= link_to 'Back', notices_path