config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'home/index'
  get 'home/profile'
  get 'download/import_xls/:name', to: 'download#import_xls', as: :download_import_xls

  resources :salesman_day_tradetotals
  resource :report do
    collection do
      get :clients_days
      get :new_clients
      get :active_clients
      get :active_agents
      get :home_summary
    end
  end
  resources :jobs do
    collection do
      get 'run_job/:job', action: :run_job, as: :run_job
      get 'recal'
    end
  end
  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    member do
      get :create_login
      get :del_login
      get :del_salesman
      get :add_salesman
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades do
    collection do
      get 'client_trades/:client_id', to: 'trades#client_trades'
    end
  end
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen do
    member do
      get :set_client
    end
  end
  resources :pos_machines

  # raw data
  resources :imp_ops
  resources :imp_logs do
    member do
      get :import, :unimport, :total, :untotal
    end
  end
  resources :imp_qf_clearings
  resources :imp_qf_trades
  resources :imp_qf_customers
  resources :code_tables
  resource :summary do
    member do
      get :home_sum
    end
  end
  resources :logs do
    collection do
      get :get_log_msg
    end
  end
  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  root to: 'home#index'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/imp_logs_controller.rb
class ImpLogsController < ResourcesController
  def import
    load_object
    
  end
end

app/views/imp_logs/index.html.slim
.row
  .col-md-12
    p
      - ct = CodeTable.find_code('config', '当前对账月份')
      |当前对账月份：#{ct.val}
      - if ct.status == 0
        | (当前数据不需要重算)
      - else
        | (有修改过代理商或业务员，可能需要重算！)
        = link_to '重算当前月汇总', run_job_jobs_path('recaculate_month'), remote: true, data: {confirm: '只有在修改了商户代理之后才需要重算当月统计，确认吗？'}
    .panel.panel-success
      .panel-heading
        .panel-heading-btn
          = link_to '读取Email', run_job_jobs_path('get_qf_emails'), class: "btn btn-xs btn-primary", remote: true
          = link_to '导入Excel', run_job_jobs_path('parse_excel'), class: "btn btn-xs btn-primary", remote: true
          = link_to "导入数据", run_job_jobs_path('data_import'), class: 'btn btn-xs btn-primary', remote: true
          = link_to "统计汇总", run_job_jobs_path('trades_totals'), class: 'btn btn-xs btn-primary', remote: true
          a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-expand"
            i.fa.fa-expand
        h4.panel-title 数据导入日志
      .panel-body
        = paginate @collection
        table.table
          tbody
            - @collection.each do |obj|
              tr id="imp_log_#{obj.id}"
                td rowspan='2'
                  = obj.id
                  br
                  |(uid: 
                  = obj.uid
                  |)
                td
                  | 邮件标题
                  = obj.title
                  br/
                  h4
                    | 附件名称
                    = obj.origin_filename
                td
                  | 发件人:&nbsp;
                  = obj.mail_from
                td rowspan='2' nowrap="nowrap"
                  - if obj.status > 0 && obj.filename
                    i.fa.fa-file-excel-o &nbsp;
                    = link_to File.extname(obj.filename) + '文件', download_import_xls_path(name: "#{File.basename(obj.filename)}")
                    br
                    = link_to "商户：#{obj.imp_qf_customers.count}条/#{obj.imp_qf_customers.where(zt: 1).count}, ", imp_qf_customers_path("q[imp_log_id_eq]" => obj.id), target: 'imp_detail_win'
                    br
                    = link_to "交易：#{obj.imp_qf_trades.count}条/#{obj.imp_qf_trades.where(zt: 1).count}, ", imp_qf_trades_path("q[imp_log_id_eq]" => obj.id), target: 'imp_detail_win'
                    br
                    = link_to "清算：#{obj.imp_qf_clearings.count}条/#{obj.imp_qf_clearings.where(zt: 1).count}", imp_qf_clearings_path("q[imp_log_id_eq]" => obj.id), target: 'imp_detail_win'
                td= obj.status
              tr
                td= obj.detail
                td= obj.received_at