config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'home/index'
  get 'home/profile'
  get 'download/import_xls/:name', to: 'download#import_xls', as: :download_import_xls

  resources :salesman_day_tradetotals
  resource :report do
    collection do
      get :clients_days
      get :new_clients
      get :active_clients
      get :active_agents
      get :home_summary
    end
  end
  resources :jobs do
    collection do
      get 'run_job/:job', action: :run_job, as: :run_job
      get 'recal'
    end
  end
  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    member do
      get :create_login
      get :del_login
      get :del_salesman
      get :add_salesman
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades do
    collection do
      get 'client_trades/:client_id', to: 'trades#client_trades'
    end
  end
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen do
    member do
      get :set_client
    end
  end
  resources :pos_machines

  # raw data
  resources :imp_ops
  resources :imp_logs do
    member do
      get :import, :unimport, :total, :untotal
    end
  end
  resources :imp_qf_clearings
  resources :imp_qf_trades
  resources :imp_qf_customers
  resources :code_tables
  resource :summary do
    member do
      get :home_sum
    end
  end
  resources :logs do
    collection do
      get :get_log_msg
    end
  end
  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  root to: 'home#index'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/home_controller.rb
class HomeController < AdminController
end

app/views/home/index.html.slim
p
  | 数据导入时间：#{ l ImpLog.first.created_at if ImpLog.count > 0}，
  = link_to '数据处理', imp_logs_path, class: "btn btn-primary btn-xs"
.row
  .col-md-3
    .widget.widget-stats.bg-blue
      .stats-icon
        i.fa.fa-cny
      .stats-info
        h4 本月总交易金额
        p#month_total_amount
      .stats-link
        a href='#'
          span 总笔数 :
          span#month_total_count
  .col-md-3
    .widget.widget-stats.bg-green#weixin
      .stats-icon
        i.fa.fa-wechat
      .stats-info
        h4 本月微信交易金额
        p#month_wechart_amount
      .stats-link
        a href='#'
          span 总笔数:
          span#month_wechart_count
  .col-md-3
    .widget.widget-stats.bg-purple
      .stats-icon
        i.fa.fa-money
      .stats-info
        h4 本月T0交易金额
        p#month_t0_amount
      .stats-link
        a href='#'
          span 总笔数 :
          span#month_t0_count
  .col-md-3
    .widget.widget-stats.bg-red
      .stats-icon
        i.fa.fa-users
      .stats-info
        h3 本月新增商户
        p#month_clients_count
      .stats-link
        a href='#'
          span 总商户数 :
          span#total_clients_count

br
.row
  .col-md-12
    .panel.panel-inverse
      .panel-heading
        .btn-group.pull-right data-toggle='buttons'
          label.btn.btn-success.btn-xs#mon_trades_prev
            input#mon_trades_prev type='radio' name='options' 上一月
          label.btn.btn-xs#mon_trades_title 2015-11
          label.btn.btn-success.btn-xs#mon_trades_next
            input#mon_trades_next type='radio' name='options' 下一月
        h4.panel-title 交易汇总表
      .panel-body#mon_trades_total style='overflow:auto;'


.row
  .col-md-12
    .panel.panel-inverse
      .panel-heading
        h4.panel-title 新增商户
      .panel-body#new_clients


javascript:
  $(function(){
    var d = new Date();
    var y = d.getFullYear();
    var m = d.getMonth();

    $.getScript("#{home_summary_report_path}");
    $.getScript("#{clients_days_report_path(q: Date.today.strftime('%Y-%m'))}");
    $.getScript("#{new_clients_report_path}");
    //$.getScript("#{active_clients_report_path(q: Date.today.strftime('%Y-%m'))}");
    //$.getScript("#{active_agents_report_path(q: Date.today.strftime('%Y-%m'))}");
  });

app/views/home/profile.html.slim
/ 显示flash消息
= flash.each do |type, message|
  div class="flash"
    javascript:
      $(window).load( function() {
        setTimeout( function() {
          $.gritter.add({
            title: 'Welcome ',
            text: 'Lorem ipsum.',
            image: '/favicon.png',
            sticky: true,
            time: '',
            class_name: 'my-sticky-class'
            });
            }, 500);     
        }
      }  
      
div class='row'
  div class='col-md-10'
    h3 个人信息
    p 手机号码: #{current_user.mobile}
    p 用户名: #{current_user.name}

  div class='col-md-2'
    - if user_signed_in?
      == link_to '退出登录', destroy_user_session_path, :class =>'btn btn-warning', :method => :delete