config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'home/index'
  get 'home/profile'
  get 'download/import_xls/:name', to: 'download#import_xls', as: :download_import_xls

  resources :salesman_day_tradetotals
  resource :report do
    collection do
      get :clients_days
      get :new_clients
      get :active_clients
      get :active_agents
      get :home_summary
    end
  end
  resources :jobs do
    collection do
      get 'run_job/:job', action: :run_job, as: :run_job
      get 'recal'
    end
  end
  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    member do
      get :create_login
      get :del_login
      get :del_salesman
      get :add_salesman
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades do
    collection do
      get 'client_trades/:client_id', to: 'trades#client_trades'
    end
  end
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen do
    member do
      get :set_client
    end
  end
  resources :pos_machines

  # raw data
  resources :imp_ops
  resources :imp_logs do
    member do
      get :import, :unimport, :total, :untotal
    end
  end
  resources :imp_qf_clearings
  resources :imp_qf_trades
  resources :imp_qf_customers
  resources :code_tables
  resource :summary do
    member do
      get :home_sum
    end
  end
  resources :logs do
    collection do
      get :get_log_msg
    end
  end
  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  root to: 'home#index'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def home_summary
    @trade_month = Date.current.to_s[0..6]

    tt = CodeTable.find_by(name: 'trade_type').id
    ts = CodeTable.where('name like ?', '%微信%').where(parent_id: tt)
    d = Date.current.all_month
    @month_wechart_count10 = Trade.where(trade_date: d, trade_type_id: ts.ids).where("trade_amount >= ?", 10.0).count
    @month_clients_count = Client.where(join_date: d).count
    @total_clients_count = Client.count
  end

  def clients_days
    year = params[:q][0..3].to_i
    month = params[:q][5..7].to_i
    dt = Date.new(year, month, 1)
    @prev_month = dt - 1.month
    @next_month = dt + 1.month
    ts = TradeSum.where(
      sum_obj_type: 'ALL',
      sum_type: :day,
      trade_date: dt.all_month)
      .order("trade_date ASC")
    @collection = ts.group_by{|t| t.trade_date}
  end

  def new_clients
    @collection = Client.order("join_date DESC").take(10)
  end

  def active_clients
    year = params[:q][0..3].to_i
    month = params[:q][5..7].to_i
    dt = Date.new(year, month, 1)
    @collection_clients = []
    idx = 0
    all = Biz::SysTotalBiz.active_clients(dt, 'total_amount')
    all.each do |t|
      idx += 1
      client = Client.find(t["client_id"])
      c = client.contacts.first
      # total = Biz::AgentTotalBiz.new(client.id)
      t["idx"] = idx
      if c
        t["contact_name"] = c.name || ''
        t["contact_tel"] = c.tel || ''
      end
      # # t['cooperation_type'] = agent.cooperation_type_id
      # t['cooperation_date'] = agent.cooperation_date
      # t["salesman_count"] = total.salesman_all.count
      # t["client_count"] = total.clients_all.count
      # t["client_new_count"] = total.new_clients.count

      t["location"] = ''
      @collection_clients << t
    end
  end

  def active_agents
    year = params[:q][0..3].to_i
    month = params[:q][5..7].to_i
    dt = Date.new(year, month, 1)
    @collection_agents = []
    idx = 0
    all = Biz::SysTotalBiz.active_agents(dt, 'total_amount')
    all.each do |t|
      idx += 1
      agent = Agent.find(t["agent_id"])
      c = agent.contacts.first
      total = Biz::AgentTotalBiz.new(agent.id)
      t["idx"] = idx
      if c
        t["contact_name"] = c.name || ''
        t["contact_tel"] = c.tel || ''
      end
      t['cooperation_type'] = agent.cooperation_type_id
      t['cooperation_date'] = agent.cooperation_date
      t["salesman_count"] = total.salesman_all.count
      t["client_count"] = total.clients_all.count
      t["client_new_count"] = total.new_clients.count

      t["location"] = ''
      @collection_agents << t
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def trade_value(objs, trade_type, attr)
    obj = objs.find{|t| t.trade_type == trade_type}
    if obj && obj.has_attribute?(attr)
      if attr == :amount
        n2 obj[attr]
      else
        n0 obj[attr]
      end
    else
      nil
    end
  end

  def trade_sum_month(trade_month, trade_type, field)
    ts = TradeSum.where(sum_obj_type: 'ALL', sum_type: 'month', trade_date: trade_month, trade_type: trade_type).first
    ts[field] if ts
  end
end

app/views/reports/_active_agents_report.html.slim
table.table
  thead
    tr
      th 排名
      th 渠道名称
      th 联系人
      th 手机
      th 合作时间
      th 业务数
      th 累计户
      th 当月户
      th 总金额
      th 微金额
      th 微笔数
      th 支金额
      th T0金额
      th 操作
  tbody
    - @collection_agents.each do |r|
      tr
        td= r["idx"]
        / td= r["name"]
        td= r["contact_name"]
        td= r["contact_tel"]
        td= r["cooperation_type"]
        td= r["cooperation_date"]
        td= r["salesman_count"]
        td= r["client_count"]
        td= r["client_new_count"]
        / 
        / td= r['salesman.count']
        / td= r['clienter.count']
        / td= r["clienter.new"]
        / 
        td= r["total_amount"]
        td= r["wechat_amount"]
        td= r["wechat_count"]
        td= r["alipay_amount"]
        td= r["t0_amount"]
        td= r["t0_count"]
        
        
        

app/views/reports/_active_clients_report.html.slim
table.table
  thead
    tr
      th 排名
      th 商户名称
      th 联系人
      th 手机
      th 地区
      th 业务员
      th 渠道
      th 入网时间
      th 费率
      th 总金额
      th 微金额
      th 微笔数
      th 支金额
      th 支笔数
      th T0金额
      th T0笔数
  tbody
    - @collection_clients.each do |r|
      tr
        td= r["idx"]
        td= r["shop_name"]
        td= r["contact_name"]
        th= r["contact_tel"]
        td= r["location"]
        td= link_to(r["salesman.name"], r["salesman.url"])
        td= r["qudao"]
        td= r['join_date']
        th= r["rate"]
        td= r["total_amount"]
        td= r["wechat_amount"]
        td= r["wechat_count"]
        td= r["alipay_amount"]
        td= r["alipay_count"]
        td= r["t0_amount"]
        td= r["t0_count"]
    

app/views/reports/_clients_days_summary.html.slim
table.table.sum-table total_columns='11' sum_float_columns='1,3,5,7,9' sum_int_columns='2,4,6,8,10'
  thead
    tr
      th 日期
      th.text-right 总交易
      th.text-right 总笔数
      th.text-right 微金额
      th.text-right 微笔数
      th.text-right 支金额
      th.text-right 支笔数
      th.text-right T0金额
      th.text-right T0笔数
      th.text-right T1金额
      th.text-right T1笔数
  tbody
    - @collection.each do |r|
      tr
        td= r[0]
        td.text-right= trade_value r[1], 'all', :amount
        td.text-right= trade_value r[1], 'all', :count
        td.text-right= trade_value r[1], 'wechat', :amount
        td.text-right= trade_value r[1], 'wechat', :count
        td.text-right= trade_value r[1], 'alipay', :amount
        td.text-right= trade_value r[1], 'alipay', :count
        td.text-right= trade_value r[1], 't0', :amount
        td.text-right= trade_value r[1], 't0', :count
        td.text-right= trade_value r[1], 't1', :amount
        td.text-right= trade_value r[1], 't1', :count

app/views/reports/_new_clients_report.html.slim
table.table
  thead
    tr
      th 商户名称
      th 手机      
      th 业务员
      th 费率
      th 入网时间
  tbody
    - @collection.each do |r|
      tr
        td= link_to r.shop_name, client_path(r)
        td= r.shop_tel
        td= link_to(r.salesman.name, salesman_path(r.salesman))
        td= r.rate
        td= r.join_date

app/views/reports/active_agents.js.erb
$('#active_agents')
  .html("<%=j render 'active_agents_report' %>");

app/views/reports/active_clients.js.erb
$('#active_clients')
  .html("<%=j render 'active_clients_report' %>");

app/views/reports/clients_days.html.slim
= render 'clients_days_summary'

app/views/reports/clients_days.js.erb
$('#mon_trades_total')
  .html("<%=j render 'clients_days_summary' %>");
table_summary();

$('#mon_trades_title').text("<%= params[:q] %>");
$('#mon_trades_prev').unbind('click').click(function(){
  $.getScript("<%= clients_days_report_path(q: @prev_month.strftime('%Y-%m')) %>");
});
$('#mon_trades_next').unbind('click').click(function(){
  $.getScript("<%= clients_days_report_path(q: @next_month.strftime('%Y-%m')) %>");
});

app/views/reports/home_summary.js.erb
$('#month_total_amount').text('<%=n2 trade_sum_month(@trade_month, "all", "amount") %>');
$('#month_total_count').text('<%=n0 trade_sum_month(@trade_month, "all", "count") %>');

$('#month_wechart_amount').text('<%=n2 trade_sum_month(@trade_month, "wechat", "amount") %>');
$('#month_wechart_count').text('<%=n0 trade_sum_month(@trade_month, "wechat", "count") %>');
$('#month_wechart_count10').text('<%=n0 @month_wechart_count10 %>');

$('#month_t0_amount').text('<%=n2 trade_sum_month(@trade_month, "t0", "amount") %>');
$('#month_t0_count').text('<%=n0 trade_sum_month(@trade_month, "t0", "count") %>');

$('#month_clients_count').text('<%=n0 @month_clients_count %>');
$('#total_clients_count').text('<%=n0 @total_clients_count %>');

app/views/reports/new_clients.js.erb
$('#new_clients')
  .html("<%=j render 'new_clients_report' %>");